### ISSUE TITLE
[BUG] dict key 입력 및 JSON 변환 코드 수정 요청

### ISSUE THREAD

**Issue by seahahn** [AI-Play/ML-Train#37]
### 작성자

안경호

### make_model.py

```python
# make_pipeline

# before
    if scaler is not None:
        try: steps.append((scaler, SCALERS[scaler](**params[scaler])))
        except: return "올바르지 않은 스케일러 이름"
    
    if model is not None:
        try: steps.append((model, MODELS[model](**params[model])))
        except: return "올바르지 않은 모델 이름"

# after
    if scaler is not None:
        try: steps.append((scaler, SCALERS[scaler](**params["scaler"])))
        except: return "올바르지 않은 스케일러 이름"

    if model is not None:
        try: steps.append((model, MODELS[model](**params["model"])))
        except: return "올바르지 않은 모델 이름"
```
item을 통해 들어온 JSON의 키값 자체를 가져와야 하기 때문에
scaler와 model 변수가 아니라 문자열로 받아야 하네요.

### model_functions.py

1. make_model import 경로
```python
# before
from make_model import MODELS, BUCKET

# after
from .make_model import MODELS, BUCKET
```

2. ~model_steps~ model_transform 내 JSON 변환 코드
```python
# before
X = json.loads(await item.json())

# after
X = await item.json()
```

3. model_fit_transform dict 키값
위 make_model의 경우와 동일합니다.
```python
# before
    X_train = pd.read_json(item[X_train])
    if "y_train" in item:
        y_train = pd.read_json(item[y_train])
    else:
        y_train = None

# after
    X_train = pd.read_json(item["X_train"])
    if "y_train" in item:
        y_train = pd.read_json(item["y_train"])
    else:
        y_train = None
```

### 2. 기대 사항

위 사항이 반영되면 함수가 정상 동작할 것으로 기대합니다.

### 3-1. 운영체제

윈도우 10

### 3-2. 개발 도구

VSCode

### 3-3. 작업하신 개발 환경을 알려주세요. (다중 선택 가능)

localhost

**Comment by KayyoungHL** [comment]
#### 1. make_model import 경로
수정하였습니다.

#### 2. model_steps 내 JSON 변환 코드
```python
# before
X = json.loads(await item.json())

# after
X = pd.read_json(await item.json())
```
pd.read_json 으로 수정하였습니다.

#### 3. model_fit_transform dict 키값
수정하였습니다.

**Comment by seahahn** [comment]
> ### make_model.py
> 수정하였습니다.
> 
> ### model_functions.py
> #### 1. make_model import 경로
> 수정하였습니다.
> 
> #### 2. model_steps 내 JSON 변환 코드
> ```python
> # before
> X = json.loads(await item.json())
> 
> # after
> X = pd.read_json(await item.json())
> ```
> 
> model_steps가 아니라 transform이 맞겠죠? trainsform의 해당 내용을 pd.read_json 으로 수정하였습니다.
> 
> #### 3. model_fit_transform dict 키값
> 수정하였습니다.

transform이 맞아요. 잘못 갖다 붙였나보네요.
고생하셨습니다! 풀리퀘 올려주시면 바로 반영할게요
